apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Universal CI - ${{ env.APP_NAME }}
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
env:
  APP_NAME: squid-ui
  LANGUAGE: node
  COVERAGE_ROOT: src
  DEBUG: "true"
  # Deployment target: squid-integ
  

jobs:
  test:
    uses: github.com/squidstack/squidstack/.cloudbees/workflows/test-generic.yaml@main
    with:
      app_name: squid-ui
      language: node
      coverage_root: src
      debug: "true"
      enable_smart_tests: "true"
    secrets: inherit
    vars: inherit

  build:
    uses: github.com/squidstack/squidstack/.cloudbees/workflows/build-generic.yaml@main
    with:
      app_name: squid-ui
      docker_user: ${{ vars.DOCKER_USER }}
      commit_sha: ${{ cloudbees.scm.sha }}
      push_latest: "true"
      debug: "true"
    secrets:
      docker_token: ${{ secrets.DOCKER_TOKEN }}
    vars: inherit

  deployDev:
    if: ${{ cloudbees.scm.branch != 'main' }}
    environment: squid-dev
    uses: github.com/squidstack/squidstack/.cloudbees/workflows/deploy-generic.yaml@main
    needs: [test, build]
    with:
      component_name: squid-ui
      environment_name: squid-dev
      docker_repo: ${{ vars.DOCKER_USER }}/squid-ui
      artifact_id: ${{ needs.build.outputs.PRIMARY_ARTIFACT_ID }}
      version: ${{ needs.build.outputs.VERSION }}
      commit_sha: ${{ cloudbees.scm.sha }}
      hostname: squid-dev.aib-unify-demo.sa-demo.beescloud.com
      feature_flags_enabled: "true"
    secrets: inherit
    vars: inherit

  deployInteg:
    if: ${{ cloudbees.scm.branch == 'main' }}
    environment: squid-integ
    uses: github.com/squidstack/squidstack/.cloudbees/workflows/deploy-generic.yaml@main
    needs: [test, build]
    with:
      component_name: squid-ui
      environment_name: squid-integ
      docker_repo: ${{ vars.DOCKER_USER }}/squid-ui
      artifact_id: ${{ needs.build.outputs.PRIMARY_ARTIFACT_ID }}
      version: ${{ needs.build.outputs.VERSION }}
      commit_sha: ${{ cloudbees.scm.sha }}
      hostname: squid-integ.aib-unify-demo.sa-demo.beescloud.com
      feature_flags_enabled: "true"
    secrets: inherit
    vars: inherit

  triggerRelease:
    if: ${{ cloudbees.scm.branch == 'main' }}
    needs: [test, build, deployInteg]
    uses: github.com/squidstack/squidstack/.cloudbees/workflows/release-generic.yaml@main
    with:
      component_name: squid-ui
      component_id: "1c1bf9f6-12d8-49c8-8333-0898b2ec255b"
      version: ${{ needs.build.outputs.VERSION }}
      smart_tests_build_name: ${{ needs.test.outputs.SMART_TESTS_BUILD_NAME }}
      environment: squid-preprod
      release_name_prefix: "squid-ui"
    secrets: inherit
    vars: inherit  